- name: Create cables between two devices
  netbox.netbox.netbox_cable:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      termination_a_type: dcim.interface
      termination_a:
        device: "{{ item.termination_a_device }}"
        name: "{{ item.termination_a_name }}"
      termination_b_type: dcim.interface
      termination_b:
        device: "{{ item.termination_b_device }}"
        name: "{{ item.termination_b_name }}"
    state: present
  loop: "{{ netbox_cables }}"
