- name: Register system
  include_tasks: register_servers.yaml
  loop: "{{ netbox_servers|subelements('servers') }}"
  loop_control:
    loop_var: server
    label: "{{ server.1.name }}"

- name: Register NICs
  include_tasks: register_nics.yaml
  loop: "{{ netbox_servers|subelements('servers') }}"
  loop_control:
    loop_var: server
    label: "{{ server.1.name }}"
