- name: Create manufacturer
  netbox.netbox.netbox_manufacturer:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ item.1.manufacturer }}"
    state: present

- name: Create the device_type
  netbox.netbox.netbox_device_type:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      manufacturer: "{{ item.1.manufacturer }}"
      model: "{{ item.1.model }}"
      u_height: "{{ item.1.height }}"
      subdevice_role: "child"
    state: present
  when: item.1.height == 0

- name: Create the device_type
  netbox.netbox.netbox_device_type:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      manufacturer: "{{ item.1.manufacturer }}"
      model: "{{ item.1.model }}"
      u_height: "{{ item.1.height }}"
    state: present
  when: item.1.height !=0

- name: Create device role
  netbox.netbox.netbox_device_role:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ item.1.role }}"
    state: present

- name: Register system in netbox
  netbox.netbox.netbox_device:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ item.1.name }}"
      device_type: "{{ item.1.model }}"
      location: "{{ item.0.location }}"
      rack: "{{ item.0.rack }}"
      device_role: "{{ item.1.role }}"
      site: "{{ item.0.site }}"
    state: present

- name: Set device's position within rack
  netbox.netbox.netbox_device:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ item.1.name }}"
      position: "{{ item.1.rackpos }}"
      face: front
    state: present
  when: item.1.parent_device is not defined

- name: Add device to bay
  netbox.netbox.netbox_device_bay:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      installed_device: "{{ item.1.name }}"
      name: "{{ item.1.parent_device_bay }}"
      device: "{{ item.1.parent_device }}"
    state: present
  when: item.1.parent_device is defined
