- name: "Create device types"
  connection: local
  hosts: localhost
  gather_facts: false

  tasks:
    - name: create some 1U dell servers
      netbox.netbox.netbox_device_type:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          model: "{{ item }}"
          manufacturer: dell
        state: present
      loop:
        - PowerEdge R620
        - PowerEdge R630

    - name: create some 2U dell servers
      netbox.netbox.netbox_device_type:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          model: "{{ item }}"
          manufacturer: dell
          u_height: 2
        state: present
      loop:
        - PowerEdge R720
        - PowerEdge R730

    - name: create cisco server
      netbox.netbox.netbox_device_type:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          model: C220
          manufacturer: cisco
        state: present
