all:
  children:
    servers:
      children:
        production_ceph:
          hosts:
            kzn-mon1:
              ansible_host: 172.16.19.14
            kzn-mon2:
              ansible_host: 172.16.17.14
            kzn-mon3:
              ansible_host: 172.16.5.14
            kzn-osd07:
              ansible_host: 172.16.5.15
          vars:
            ansible_user: root
        openstack_computes:
          hosts:
            neu-3-35:
              ansible_host: 172.16.3.35
          vars:
            ansible_user: root
    switches:
      hosts:
        brocade-3-43:
          ansible_host: 10.0.3.43
          ansible_user: admin
          ansible_network_os: nos
          ansible_password: null
        cisco-19-42:
          ansible_host: 10.0.19.42
          ansible_user: admin
          ansible_password: null
          ansible_network_os: cisco.nxos.nxos
        cisco-17-42:
          ansible_host: 10.0.17.42
          ansible_user: admin
          ansible_password: null
          ansible_network_os: cisco.nxos.nxos
      vars:
        ansible_connection: ansible.netcommon.network_cli
