- name: "Gather required information"
  hosts: ipmi_switches
  gather_facts: false
  tasks:

    - name: "Calcuate rack, rackpos and set device attributes"
      set_fact:
        rack: "{{ parsed_address[-2] }}"
        rackpos: "{{ parsed_address[-1] }}"
        device_role: "ipmi_switches"
        manufacturer: "{{ ('brocade_icx' in group_names) | ternary('Brocade', 'IBM') }}"
        model: "{{ ('brocade_icx' in group_names) | ternary('brocade_icx', 'RackSwitch G8000') }}"
      vars:
        parsed_address: "{{ ansible_host | split('.') }}"

    - name: "Create device role based on ansible group"
      netbox.netbox.netbox_device_role:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{ device_role }}"
        state: present
      delegate_to: 127.0.0.1

    - name: "Create the device_type"
      ignore_errors: true
      netbox.netbox.netbox_device_type:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          manufacturer: "{{ manufacturer }}"
          model: "{{ model }}"
        state: present
      delegate_to: 127.0.0.1

    - name: "Register the device in netbox"
      netbox.netbox.netbox_device:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{ inventory_hostname }}"
          device_type: "{{ model }}"
          rack: "{{ 'row3/podB/cage' + rack }}"
          position: "{{rackpos}}"
          device_role: "{{ device_role }}"
          face: front
          location: Row 3 Pod B
          site: MGHPCC
        state: present
      delegate_to: 127.0.0.1

    - name: "Create 1G network interfaces"
      netbox.netbox.netbox_device_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: >-
            GigabitEthernet 1/1/{{item}}
          device: "{{ inventory_hostname }}"
          type: 1000Base-t (1GE)
        state: present
      delegate_to: 127.0.0.1
      loop: "{{ range(1, 48 + 1, 1)|list }}"

    - name: "Create management interface of the switch"
      netbox.netbox.netbox_device_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          device: "{{ inventory_hostname }}"
          name: management
          type: 1000Base-t (1GE)
          mgmt_only: true
        state: present
      delegate_to: 127.0.0.1

    - name: "Associate IP address with management interface"
      netbox.netbox.netbox_ip_address:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          address: "{{ ansible_host }}"
          assigned_object:
            name: management
            device: "{{ inventory_hostname }}"
        state: present
      delegate_to: 127.0.0.1
