- name: "Create sites"
  connection: local
  hosts: localhost
  gather_facts: False

  tasks:
    - name: Create MGHPCC site
      netbox_site:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: MGHPCC
        state: present

    - name: Create PRB site
      netbox_site:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: BU PRB
        state: present

    - name: Create OCT site group
      netbox.netbox.netbox_site_group:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: OCT
          description: Open Cloud Testbed (UMass)
        state: absent

    - name: Create MOC site group
      netbox.netbox.netbox_site_group:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: MOC
          description: Mass Open Cloud cages
        state: absent
