- name: "Create sites"
  connection: local
  hosts: localhost
  gather_facts: False

  tasks:
    - name: Create MGHPCC site
      netbox_site:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: MGHPCC
        state: present

    - name: Create PRB site
      netbox_site:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: BU PRB
        state: present
