netbox_racks:
  - site: MGHPCC
    location: Row3/PodB
    u_height: 44
    racks:
      - name: Row3/PodB/Cage3
      - name: Row3/PodB/Cage5
      - name: Row3/PodB/Cage15
      - name: Row3/PodB/Cage17
      - name: Row3/PodB/Cage19

  - site: MGHPCC
    location: Row4/PodA
    u_height: 44
    racks:
      - name: Row4/PodA/Cage2
      - name: Row4/PodA/Cage4
      - name: Row4/PodA/Cage21
      - name: Row4/PodA/Cage23
