- name: Create sites
  netbox.netbox.netbox_site:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ item.name }}"
      description: "{{ item.description|default(omit) }}"
    state: present
  loop: "{{ netbox_sites }}"

- name: Create locations
  netbox.netbox.netbox_location:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ item.name }}"
      site: "{{ item.site }}"
      description: "{{ item.description|default(omit) }}"
    state: present
  loop: "{{ netbox_locations }}"
